### ISSUE TITLE
Swagger reads unrelated information

### ISSUE THREAD

**Issue by Aristona** [theo4u/sails-hook-swagger-generator#20]
Hi,

This is how my Swagger UI looks like.

![image](https://user-images.githubusercontent.com/2160002/37334990-14deb180-26b6-11e8-88cb-4c8568dda456.png)

My route:

![image](https://user-images.githubusercontent.com/2160002/37335042-2f5f50be-26b6-11e8-9180-e921fcf80b11.png)

My controller:

![image](https://user-images.githubusercontent.com/2160002/37335086-416b1950-26b6-11e8-9d9a-652a46f006ad.png)

Why Swagger reads the property ID, and why does it read "body" object twice? Am I doing something wrong?

Ps. Token is coming from policies, but there is nothing related to ID in the policies.

**Comment by theo4u** [comment]
hmmm what version of sailsjs are you using ?

**Comment by Aristona** [comment]
@theo4u ^0.12.13

**Comment by theo4u** [comment]
will look into this soon

**Comment by Aristona** [comment]
Any news about it @theo4u ?

**Comment by theo4u** [comment]
Oh, from observing the screenshots, the issue is with the `Route.group` seeing it as a separate controller I guess, if you can create a sample repo with this implementation, so I can pull and run through it

**Comment by theo4u** [comment]
Oh, from observing the screenshots, the issue is with the Route.group seeing it as a separate controller I guess, if you can create a sample repo with this implementation, so I can pull and run through it @Aristona

**Comment by Aristona** [comment]
@theo4u I'll normalize the routes file and try. If I'm out of luck, I'll ask for your help

**Comment by theo4u** [comment]
@Aristona ok np 👍

**Comment by Aristona** [comment]
@theo4u I cleared my routes.js file. It still reads the routes from somewhere. Does it read all the controllers and their methods or something?

**Comment by Aristona** [comment]
@theo4u I turned it off, didn't help

**Comment by theo4u** [comment]
turning it off, still generates default blueprints routes, **weird behaviour here**
and also **duplication of records**

Would test for both errors again, if you can upload a sample repo with your configuration, so i can pull and test with

**Comment by Aristona** [comment]
@theo4u I'll do it next week probably. Will ping you when I'm done
