### ISSUE TITLE
Disabling swagger-generator on non-development environments.

### ISSUE THREAD

**Issue by Aristona** [theo4u/sails-hook-swagger-generator#21]
Hi,

Is there any way to disable this module in non-development environments?

**Comment by theo4u** [comment]
not implemented, you can check this
http://stackoverflow.com/a/21612024/486547
https://github.com/balderdashy/sails/issues/1077

**Comment by Aristona** [comment]
Can we put a parameter into your package, such as: `disabled: true`? If it's possible, I can work on a PR.

**Comment by theo4u** [comment]
yea cool, np, also update the readme so others can easily use it
