### ISSUE TITLE
Improper routes handling

### ISSUE THREAD

**Issue by atte-backman** [theo4u/sails-hook-swagger-generator#24]
When I'm having routes configured e.g.:

    'get /user/:id/creditCards': {
        controller: 'user',
        action: 'get-or-create'
    }

the generated json shows incorrectly

    /user/{id/creditCards}

P.S. I'm using sailsjs 1.0

**Comment by theo4u** [comment]
oh, will give this a try and possibly send a fix

**Comment by alexschwarz89** [comment]
+1 for fixing this
