### ISSUE TITLE
Swagger UI

### ISSUE THREAD

**Issue by pavanmehta91** [theo4u/sails-hook-swagger-generator#27]
I'm able to generate the JSON file in the ./swagger folder. How do I integrate swagger UI along with it in a sails app on some path say /swagger-api/

**Comment by theo4u** [comment]
you can simply change the directory you want to place the generated swagger json may be assets, then clone https://github.com/swagger-api/swagger-ui following the instructions [here](https://swagger.io/docs/swagger-tools/#download-33) 

Update the path to the json to the within your `assets` folder

**Comment by pavanmehta91** [comment]
Thanks :)

**Comment by ryandmello1198** [comment]
> you can simply change the directory you want to place the generated swagger json may be assets, then clone https://github.com/swagger-api/swagger-ui following the instructions [here](https://swagger.io/docs/swagger-tools/#download-33)
> 
> Just simply extract the `dist` folder (which is needed for just the swagger ui) and update this line https://github.com/swagger-api/swagger-ui/blob/1a95b9e9c972b95227a2976553fea988e58d7ff2/dist/index.html#L44 to be the path to the generated swagger json within your `assets` folder

Where to extract the `dist` folder?
