### ISSUE TITLE
Not defined Models

### ISSUE THREAD

**Issue by sudograce** [theo4u/sails-hook-swagger-generator#40]
Hello.
I have a problem with model definitions. I use sequelize.
What should I do to make the data for the model (#/definitions/{{modelName}}) pull up from the model itself? Because now it is empty.

![image of swagger model](https://i.ibb.co/hZbHtK7/2018-12-20-17-23-27.png)

Model example:
```js
module.exports = function (sequelize, DataTypes) {
  var activities = sequelize.define("activities", {
    removed: {
      type: DataTypes.BOOLEAN,
      defaultValue: false
    },
    name: {
      type: DataTypes.STRING,
      allowNull: false,
      defaultValue: false
    },
    createdAt: {
      type: DataTypes.DATE
    },
    updatedAt: {
      type: DataTypes.DATE
    },
    agencyId: {
      type: DataTypes.INTEGER,
      references: {
        model: "companies",
        key: "id"
      }
    }
  });
  return activities;
};

```
I would be grateful for any help.

**Comment by theo4u** [comment]
Hmmm this lib does not support [sequelize](https://github.com/sequelize/sequelize#readme), just leveraging on sails integration with [waterline](https://github.com/balderdashy/waterline)
