### ISSUE TITLE
Disable header (token) for specific routes

### ISSUE THREAD

**Issue by sanjayradadiya** [theo4u/sails-hook-swagger-generator#46]
Hi,

I need to remove token header params for some of routes but current i can see that in all routes.

so what i need to do for that in routes.js ?

**Comment by sanjayradadiya** [comment]
Hi any update on this ?

**Comment by theo4u** [comment]
Will fix this over the weekend

**Comment by theo4u** [comment]
added a new option to exclude default parameters check here: https://github.com/theo4u/sails-hook-swagger-generator#properties-of-swagger
