### ISSUE TITLE
Not generating routes for Blueprints

### ISSUE THREAD

**Issue by murbanowicz** [theo4u/sails-hook-swagger-generator#6]
It is not generating routes for blueprints at all.

**Comment by theo4u** [comment]
Check #2, and make sure your sails config blueprint **rest** is `true`. As [swagger.json](https://github.com/theo4u/sails-hook-swagger-generator/blob/master/swagger/swagger.json) on editor.swagger.io would show you all default blueprints.

Or if not answered, you can further explain, Thanks.

**Comment by anasuya1117** [comment]
I tried changing `rest: false` but still blueprint routes are coming.How can I disable all blueprint api's ?

Even If I add my swagger object in config/routes.js it is not overriding blueprint request params.

**Comment by theo4u** [comment]
https://github.com/theo4u/sails-hook-swagger-generator/blob/12ffb0f83bf24173b337d7a32edd64deb4fce0d3/test/generators.test.js#L253

**Comment by alexschwarz89** [comment]
Hi @theo4u, i would like to have all blueprint routes in my `swagger.json` file, but i can't get it to work. I've already read #2 and the mentioned `rest` setting is set to `true`.

I've pasted the generated file into swagger editor, the headlines are visible, but no route.

I am using Sails 1.0.0 and version 2.6.0 of the generator.

**Comment by alexschwarz89** [comment]
@theo4u Thanks a lot
